// ============================================================
// Content Pipeline Orchestrator
// Coordinates the full ingestion flow:
// URL → Fetch → Extract → AI Process → Store → Link
// ============================================================

import prisma from "@/lib/prisma";
import {
  transcriptService,
  paperService,
  articleService,
  detectSourceType,
} from "@/services/content-fetcher";
import {
  extractClaimsAndSummary,
  detectThemes,
  detectContradictions,
  recalculateClaimStatus,
} from "@/services/ai-pipeline";
import { fsrs } from "@/services/fsrs";
import { IngestRequest, ProcessingStatus } from "@/types";

type ProgressCallback = (status: ProcessingStatus, detail?: string) => void;

export class ContentPipeline {
  /**
   * Process a new piece of content end-to-end (creates source record)
   */
  async process(
    userId: string,
    request: IngestRequest,
    onProgress?: ProgressCallback
  ): Promise<void> {
    const sourceType = request.type || detectSourceType(request.url || request.doi || "");
    
    // 1. Create source record in PENDING state
    const source = await prisma.source.create({
      data: {
        userId,
        type: sourceType,
        status: "PENDING",
        title: "Processing...",
        url: request.url,
        doi: request.doi,
        userNotes: request.userNotes,
      },
    });

    await this.runPipeline(userId, source.id, sourceType, request, onProgress);
    return source.id;
  }

  /**
   * Process an already-created source record (for async background processing)
   */
  async processExistingSource(
    userId: string,
    sourceId: string,
    request: IngestRequest,
    onProgress?: ProgressCallback
  ): Promise<void> {
    const source = await prisma.source.findUnique({ where: { id: sourceId } });
    if (!source) throw new Error("Source not found");
    const sourceType = source.type as string;
    // Use URL from DB record (more reliable than request passthrough)
    const url = source.url || source.doi || request.url || request.doi || "";
    console.log(`[Pipeline] DEBUG: sourceType=${sourceType}, url=${url}`);
    await this.runPipeline(userId, sourceId, sourceType, { ...request, url }, onProgress);
  }

  /**
   * Core pipeline logic
   */
  private async runPipeline(
    userId: string,
    sourceId: string,
    sourceType: string,
    request: IngestRequest,
    onProgress?: ProgressCallback
  ): Promise<void> {
    try {
      // 2. FETCH — retrieve the content
      onProgress?.("FETCHING", "Retrieving content from source...");
      await this.updateStatus(sourceId, "FETCHING");

      const content = await this.fetchContent(sourceType, request.url || request.doi || "");

      await prisma.source.update({
        where: { id: sourceId },
        data: {
          title: content.title,
          author: content.author,
          publicationDate: content.publicationDate
            ? new Date(content.publicationDate)
            : null,
          rawText: content.text,
          journal: content.metadata.journal,
          abstract: content.metadata.abstract,
          podcastName: content.metadata.podcastName,
          episodeNumber: content.metadata.episodeNumber,
          durationSeconds: content.metadata.durationSeconds,
        },
      });

      // 3. EXTRACT — AI processes the raw text into structured data
      onProgress?.("EXTRACTING", "Extracting claims and generating summary...");
      await this.updateStatus(sourceId, "EXTRACTING");

      const extraction = await extractClaimsAndSummary(
        content.text,
        content.title,
        sourceType
      );

      await prisma.source.update({
        where: { id: sourceId },
        data: {
          summary: extraction.summary,
          keyTakeaways: JSON.stringify(extraction.keyTakeaways),
        },
      });

      // 4. PROCESS — detect themes and create claim records
      onProgress?.("PROCESSING", "Detecting themes and categorizing...");
      await this.updateStatus(sourceId, "PROCESSING");

      // Get existing themes for matching
      const existingThemes = await prisma.theme.findMany({
        select: { id: true, name: true },
      });
      const existingThemeNames = existingThemes.map((t) => t.name);

      const themeSuggestions = await detectThemes(
        extraction.claims,
        content.title,
        extraction.summary,
        existingThemeNames
      );

      // Create any new themes
      const themeMap = new Map<string, string>(); // name -> id
      for (const suggestion of themeSuggestions) {
        if (suggestion.isNew) {
          const newTheme = await prisma.theme.create({
            data: {
              name: suggestion.name,
              slug: suggestion.name.toLowerCase().replace(/\s+/g, "-"),
              isAutoGenerated: true,
            },
          });
          themeMap.set(suggestion.name, newTheme.id);
        } else {
          const existing = existingThemes.find(
            (t) => t.name.toLowerCase() === suggestion.name.toLowerCase()
          );
          if (existing) themeMap.set(suggestion.name, existing.id);
        }
      }

      // Link source to themes
      for (const suggestion of themeSuggestions) {
        const themeId = themeMap.get(suggestion.name);
        if (themeId) {
          await prisma.sourceTheme.create({
            data: {
              sourceId: sourceId,
              themeId,
              relevance: suggestion.relevance,
            },
          });
        }
      }

      // Create claim records
      const createdClaimIds: string[] = [];
      for (const claim of extraction.claims) {
        const claimRecord = await prisma.claim.create({
          data: {
            text: claim.text,
            explanation: claim.explanation,
            implications: claim.implications,
            methodology: claim.methodology,
            confidence: claim.confidence,
            status: "EMERGING",
          },
        });
        createdClaimIds.push(claimRecord.id);

        // Link claim to source
        await prisma.claimSource.create({
          data: {
            claimId: claimRecord.id,
            sourceId: sourceId,
            extractedText: claim.supportingQuote,
            timestamp: claim.timestamp,
            pageNumber: claim.pageNumber,
          },
        });

        // Link claim to themes
        for (const suggestion of themeSuggestions) {
          const themeId = themeMap.get(suggestion.name);
          if (themeId) {
            await prisma.claimTheme.create({
              data: {
                claimId: claimRecord.id,
                themeId,
                relevance: suggestion.relevance,
              },
            });
          }
        }

        // Create FSRS review card for each claim
        await prisma.reviewCard.create({
          data: {
            userId,
            claimId: claimRecord.id,
            due: new Date(),
            stability: 0,
            difficulty: 0,
            elapsedDays: 0,
            scheduledDays: 0,
            reps: 0,
            lapses: 0,
            state: 0, // New
          },
        });
      }

      // 5. LINK — detect contradictions with existing claims
      onProgress?.("LINKING", "Building knowledge graph connections...");
      await this.updateStatus(sourceId, "LINKING");

      // Get all existing claims for contradiction detection
      const allExistingClaims = await prisma.claim.findMany({
        where: {
          id: { notIn: createdClaimIds }, // exclude the claims we just created
        },
        include: {
          themes: { include: { theme: true } },
        },
      });

      if (allExistingClaims.length > 0) {
        const contradictions = await detectContradictions(
          extraction.claims,
          allExistingClaims.map((c) => ({
            id: c.id,
            text: c.text,
            themes: c.themes.map((t) => t.theme.name),
            status: c.status,
            confidence: c.confidence,
          }))
        );

        // Store contradictions
        for (const contradiction of contradictions) {
          // Find the new claim that matches
          const newClaim = await prisma.claim.findFirst({
            where: {
              text: contradiction.newClaimText,
              id: { in: createdClaimIds },
            },
          });

          if (newClaim) {
            await prisma.contradiction.create({
              data: {
                claimId: newClaim.id,
                contradictedId: contradiction.existingClaimId,
                explanation: contradiction.explanation,
                severity: contradiction.severity,
              },
            });

            // Update statuses of both claims
            if (contradiction.severity > 0.5) {
              await prisma.claim.update({
                where: { id: contradiction.existingClaimId },
                data: { status: "CONTESTED" },
              });
              await prisma.claim.update({
                where: { id: newClaim.id },
                data: { status: "CONTESTED" },
              });
            }
          }
        }
      }

      // Check if any new claims SUPPORT existing claims (same assertion, different source)
      await this.detectAndMergeSupport(createdClaimIds, allExistingClaims);

      // 6. COMPLETE
      onProgress?.("COMPLETE", "Content processed successfully!");
      await this.updateStatus(sourceId, "COMPLETE");

      // done

    } catch (error: any) {
      console.error("Pipeline error:", error);
      await prisma.source.update({
        where: { id: sourceId },
        data: {
          status: "FAILED",
          processingError: error.message || "Unknown error",
        },
      });
      throw error;
    }
  }

  /**
   * Detect when new claims support existing ones (same claim, different source)
   */
  private async detectAndMergeSupport(
    newClaimIds: string[],
    existingClaims: any[]
  ) {
    // For each new claim, check if any existing claim says essentially the same thing
    // If so, link the new source to the existing claim and upgrade its status
    const newClaims = await prisma.claim.findMany({
      where: { id: { in: newClaimIds } },
      include: { sources: true },
    });

    for (const newClaim of newClaims) {
      for (const existing of existingClaims) {
        // Simple similarity check — in production, use embeddings
        const similarity = this.textSimilarity(newClaim.text, existing.text);
        if (similarity > 0.85) {
          // These are likely the same claim from different sources
          // Link the new source to the existing claim
          const newSource = newClaim.sources[0];
          if (newSource) {
            await prisma.claimSource.create({
              data: {
                claimId: existing.id,
                sourceId: newSource.sourceId,
                extractedText: newSource.extractedText,
              },
            }).catch(() => {
              // Ignore if link already exists
            });
          }

          // Count total sources supporting this claim
          const sourceCount = await prisma.claimSource.count({
            where: { claimId: existing.id },
          });

          // Upgrade status based on source count
          if (sourceCount >= 3 && existing.status !== "CONSENSUS") {
            await prisma.claim.update({
              where: { id: existing.id },
              data: { status: "CONSENSUS" },
            });
          } else if (sourceCount >= 2 && existing.status === "EMERGING") {
            await prisma.claim.update({
              where: { id: existing.id },
              data: { status: "SUPPORTED" },
            });
          }
        }
      }
    }
  }

  /**
   * Simple text similarity (Jaccard on word sets)
   * In production, replace with embedding cosine similarity
   */
  private textSimilarity(a: string, b: string): number {
    const wordsA = new Set(a.toLowerCase().split(/\W+/).filter(w => w.length > 3));
    const wordsB = new Set(b.toLowerCase().split(/\W+/).filter(w => w.length > 3));
    const intersection = new Set([...wordsA].filter(w => wordsB.has(w)));
    const union = new Set([...wordsA, ...wordsB]);
    return union.size > 0 ? intersection.size / union.size : 0;
  }

  private async fetchContent(type: string, urlOrDoi: string) {
    switch (type) {
      case "PODCAST":
        // For podcasts, we need the audio URL
        // Spotify doesn't expose direct audio — user would need to provide
        // an audio URL or we use a podcast index API to find it
        const transcript = await transcriptService.transcribe(urlOrDoi);
        return {
          title: "Podcast Episode", // Will be overridden by metadata
          author: "Unknown",
          text: transcript.text,
          metadata: {
            type: "PODCAST" as const,
            durationSeconds: transcript.durationSeconds,
          },
        };

      case "PAPER":
        const paper = await paperService.processsPaper(urlOrDoi);
        if (!paper) throw new Error("Paper not found");
        return paper;

      case "ARTICLE":
        return await articleService.extractArticle(urlOrDoi);

      default:
        throw new Error(`Unknown source type: ${type}`);
    }
  }

  private async updateStatus(sourceId: string, status: ProcessingStatus) {
    await prisma.source.update({
      where: { id: sourceId },
      data: { status },
    });
  }
}

export const contentPipeline = new ContentPipeline();
export default contentPipeline;
