// GET /api/themes
// List all themes with source counts, claim counts, retention stats

import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { fsrs } from "@/services/fsrs";

const MVP_USER_ID = "user_mvp";

export async function GET(request: NextRequest) {
  const themes = await prisma.theme.findMany({
    include: {
      sources: { select: { sourceId: true } },
      claims: {
        include: {
          claim: {
            include: {
              reviewCards: {
                where: { userId: MVP_USER_ID },
                select: { stability: true, lastReview: true, state: true, due: true },
              },
              contradicts: { select: { id: true } },
              contradictedBy: { select: { id: true } },
            },
          },
        },
      },
    },
    orderBy: { name: "asc" },
  });

  const themeStats = themes.map((theme) => {
    const claims = theme.claims.map((ct) => ct.claim);
    const cards = claims
      .flatMap((c) => c.reviewCards)
      .filter((card) => card.lastReview !== null);

    const avgRetention =
      cards.length > 0
        ? cards.reduce((sum, card) => {
            return sum + fsrs.getRetrievability({
              due: card.due,
              stability: card.stability,
              difficulty: 0,
              elapsedDays: 0,
              scheduledDays: 0,
              reps: 0,
              lapses: 0,
              state: card.state,
              lastReview: card.lastReview,
            });
          }, 0) / cards.length
        : 0;

    const dueCount = claims.reduce((count, claim) => {
      const card = claim.reviewCards[0];
      if (card && new Date(card.due) <= new Date()) return count + 1;
      return count;
    }, 0);

    const contradictionCount = claims.reduce((count, claim) => {
      return count + claim.contradicts.length + claim.contradictedBy.length;
    }, 0);

    return {
      id: theme.id,
      name: theme.name,
      slug: theme.slug,
      icon: theme.icon || "📂",
      color: theme.color || "#00e5ff",
      bgColor: theme.bgColor || "#0a0f1a",
      sourceCount: theme.sources.length,
      claimCount: claims.length,
      avgRetention,
      dueForReview: dueCount,
      contradictionCount: Math.floor(contradictionCount / 2), // each contradiction is counted twice
      isAutoGenerated: theme.isAutoGenerated,
    };
  });

  // Filter out empty themes
  const nonEmpty = themeStats.filter((t) => t.sourceCount > 0 || t.claimCount > 0);

  return NextResponse.json({ success: true, data: nonEmpty });
}

// POST /api/themes — create a new theme manually
export async function POST(request: NextRequest) {
  const body = await request.json();

  if (!body.name || typeof body.name !== "string") {
    return NextResponse.json({ success: false, error: "Name is required" }, { status: 400 });
  }

  const slug = body.name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");

  const theme = await prisma.theme.create({
    data: {
      name: body.name,
      slug,
      description: body.description,
      icon: body.icon,
      color: body.color,
      bgColor: body.bgColor,
      isAutoGenerated: false,
    },
  });

  return NextResponse.json({ success: true, data: theme }, { status: 201 });
}
